name: Deploy existing binary to Pi

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Копируем уже существующий бинарник из репо
      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/projects/solo_leveling_bot
            # останавливаем текущий бот
            systemctl stop gym_bot || true
            # копируем бинарник из репо
            cp ${{ github.workspace }}/arm7_gym_bot ./solo_leveling_bot
            # перезапускаем сервис
            systemctl start gym_bot
